# Generated by Django 4.1 on 2022-09-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Outfit', 'Outfit'), ('Watch', 'Watch'), ('Digital', 'Digital'), ('Books', 'Books')], max_length=100, null=True),
        ),
    ]
