# Generated by Django 4.1 on 2022-09-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_customer_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='static/img/profilepic'),
        ),
    ]
