# Generated by Django 4.1 on 2022-09-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_customer_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sended',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
